### ISSUE TITLE
Add store links

### ISSUE THREAD

**Issue by jzbz** [crypto-power/website-old#9]
Important to have direct links to Cryptopower on the Google and Apple app stores on the website.

Also consider adding app store links to the very top of:
https://github.com/crypto-power/cryptopower/blob/master/README.md

**Comment by dreacot** [comment]
Google Playstore link: https://play.google.com/store/apps/details?id=com.dreacotdigital.cryptopower.mainnet

Apple Appstore link: https://apps.apple.com/ca/app/cryptopower-wallet/id6472668308
